swagger: "2.0"
info:
  description: "code test drive"
  version: "0.1"
  title: "khazad-dum"
  contact:
    email: "kmell@protonmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/"
tags:
  - name: "status"
    description: ""
  - name: "item"
    description: ""
schemes:
  - "http"
paths:
  /status:
    get:
      tags:
        - "status"
      summary: ""
      description: ""
      operationId: "getStatus"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Status"
  /item:
    get:
      tags:
        - "item"
      summary: ""
      description: ""
      operationId: "getItemById"
      produces:
        - "application/json"
      parameters:
        - name: "id"
          in: "query"
          description: ""
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/GetItemResponse"
    post:
      tags:
        - "item"
      summary: ""
      description: ""
      operationId: "postItem"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "item"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/PostItemRequest"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/PostItemResponse"
definitions:
  Status:
    type: "object"
    properties:
      dateTime:
        type: "string"
      message:
        type: "string"
    example:
      dateTime: "2021-02-05T15:35:34.701-05:00[America/Bogota]"
      message: "UP!"
  Item:
    type: "object"
    properties:
      id:
        type: "integer"
      name:
        type: "string"
      isActive:
        type: "boolean"
      price:
        type: "integer"
        format: "int64"
    example:
      id: "1001"
      name: "Cappuccino"
      isActive: true
      price: 3.22
  GetItemResponse:
    type: "object"
    properties:
      dateTime:
        type: "string"
      item:
        $ref: "#/definitions/Item"
    example:
      dateTime: "2021-02-05T15:22:00.801-05:00[America/Bogota]"
      item:
        id: "1002"
        name: "Americano"
        isActive: true
        price: 5.10
  PostItemRequest:
    type: "object"
    properties:
      item:
        $ref: "#/definitions/Item"
    example:
      item:
        id: "1003"
        name: "Espresso"
        isActive: false
        price: 2.2
  PostItemResponse:
    type: "object"
    properties:
      dateTime:
        type: "string"
      item:
        $ref: "#/definitions/Item"
    example:
      dateTime: "2021-02-05T15:30:50.122-05:00[America/Bogota]"
      item:
        id: "1004"
        name: "Caffe Latte"
        isActive: true
        price: 7.33
